apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: us.gcr.io/helical-gist-348512/app:1.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-cm  